[package]
name = "shrimply-keyframe-graph-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
shrimply-discrete-keyframe-graph-ui = { path = "../discrete-keyframe-graph-ui" }
shrimply-cross-ui-theme = { path = "../../ui/cross-ui-theme" }
shrimply-interpolation = { path = "../../interpolation" }
shrimply-math-core = { path = "../../math/core" }
shrimply-ui-foundation = { path = "../../ui/ui-foundation" }
shrimply-math-color = { path = "../../math/color" }
skia-safe = { workspace = true, features = ["gl", "textlayout"] }
shrimply-skia-adw-ui = { path = "../../ui/skia-adw-ui" }
uuid = { workspace = true, features = ["v4", "serde"] }
