[package]
name = "shrimply-skia-adw-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
hashbrown.workspace = true
async-channel.workspace = true
cached.workspace = true
shrimply-math-color = { path = "../../math/color", features = ["skia"] }
shrimply-math-geometry = { path = "../../math/geometry", features = ["skia"] }
skia-safe = { workspace = true, features = ["gl", "vulkan", "textlayout", "svg"] }
